version: '3.7'
services:
  jenkins:
    image: jenkins-dind
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    ports:
      - 5555:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

# volumes:
#   jenkins_home: